version: '2'

services:
  # MySQL
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - /D/Documents/WNMP/mysql-conf/my.cnf:/etc/mysql/my.cnf
      - /D/Documents/WNMP/mysql-conf/conf.d:/etc/mysql/conf.d
      - /D/Documents/WNMP/mysql-log:/var/log 
      - /D/Documents/WNMP/mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    container_name: mysql

  # PHP
  myphp-fpm:
    image: php:fpm
    ports:
      - "9000:9000"
    volumes:
      - /D/Documents/WNMP/php-conf/php.ini:/usr/local/etc/php/php.ini  
      - /D/Documents/WNMP/php-conf/conf.d:/usr/local/etc/php/conf.d 
      - /D/Documents/WNMP/php-log:/var/log/php 
      - /D/Documents/WeiYunSync/07 Note/105 Code/html:/data/html 
    links:
      - mysql:mysql
    container_name: myphp-fpm

  # nginx
  mynginx:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - /D/Documents/WNMP/nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - /D/Documents/WNMP/nginx-conf/conf.d:/etc/nginx/conf.d
      - /D/Documents/WNMP/nginx-log:/var/log/nginx
      - /D/Documents/WeiYunSync/07 Note/105 Code/html:/data/html
    links:
      - mysql:mysql
      - myphp-fpm:php 
    container_name: mynginx


